version: '2'
services:
    wordpress:
      image: wordpress
      links:
        - wordpress_db:mysql
      ports:
        - 8080:80
      volumes:
            - .\projectname\wp-content:/var/www/html/wp-content
      environment:
          WORDPRESS_DB_NAME: dbname
          WORDPRESS_DB_PASSWORD: password
#      restart: unless-stopped

    wordpress_db:
      image: mysql
      volumes:
        - .\docker\database:/var/lib/mysql
        - .\docker\importDatabase:/docker-entrypoint-initdb.d

      environment:
        MYSQL_ROOT_PASSWORD: password


    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - wordpress_db:mysql
      ports:
        - 8181:80
      environment:
        PMA_HOST: wordpress_db
        PMA_USER: root
        PMA_PASSWORD: password
