wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
  volumes:
        - .\wp-content:/var/www/html/wp-content
  environment:
      WORDPRESS_DB_NAME: exampledatabase
      WORDPRESS_DB_PASSWORD: examplepass
wordpress_db:
  image: mariadb
  volumes:
    - .\docker\data:/docker-entrypoint-initdb.d
  environment:
    MYSQL_ROOT_PASSWORD: examplepass
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass
